feat(UserService): add an email verification process
Frachtwerk/essencium-backend pull request #506
Opened 2024-07-07 15:36 UTC by JelmenGuhlke

- #94
- add @SkipOnUpdate functionalit to skip fields during generic update
- add endpoint /verify-email to verify given token
- add changed mail massage template
- add @Validate to BaseRepository.java to enable validation

2024-07-08 10:51 UTC, pwannenmacher requested changes

2024-07-08 10:51 UTC, pwannenmacher commented on essencium-backend/src/main/java/de/frachtwerk/essencium/backend/configuration/properties/MailConfigProperties.java
> +    @Pattern(regexp = "^[^$].*")
May be replaced by `@NotEmpty` resp. `@NotBlank`

2024-07-08 10:51 UTC, pwannenmacher commented on essencium-backend/src/main/java/de/frachtwerk/essencium/backend/configuration/properties/SecurityConfigProperties.java
> +  private int eMailTokenValidityInMonths = 1;
Instead of the time span in months, you should also change to minutes here. In my opinion, the default value should be 30 minutes. Who changes their email address and then verifies it next week...?

2024-07-09 15:24 UTC, JelmenGuhlke commented on essencium-backend/src/main/java/de/frachtwerk/essencium/backend/service/AbstractUserService.java
> +  @Autowired private SecurityConfigProperties securityConfigProperties;
Ich habe hier und in `AbstractEntityService` zwei Werte mittels `@Autowired` hinzugefügt und einen weiter Konstruktor für die Testbarkeit ergänzt. Ganz sauber ist das nicht, aber andernfalls nehmen die Konstruktor Parameter langsam aber sicher überhand. Ich denke wir sollten hier über ein "Delegator-Service" nachdenken, der als konkrete Klasse in `Essencium` lebt und einfach nur als Hülle für der Injected Services dient. Dieser ist dann der einzige der im Client Code eingebunden werden muss und wir können einfach Änderungen vornehmen, ohne dass es immer eine Migration beim Client ist

2025-03-16 06:12 UTC, JelmenGuhlke commented
Im closing the PR due to outdated code references. If the issue should still be implemented, it should be done from scratch.

2025-03-16 06:12 UTC, closed without merging