refactor: renamed UserDto in core project to AbstractBaseUserDto, renamed AppUserDto in subprojects to UserDto
Frachtwerk/essencium-backend pull request #581
Opened 2024-09-05 11:16 UTC by cholakov11

Renamed UserDto class to AbstractBaseUserDto

* Although the AbstractBaseUserDto class is not defined as an abstract class, I believe it should be named as abstract. This is because in our context the dto class is used to transport data of the AbstractBaseUser class. Naming the dto class also abstract should avoid any misinterpretations that this dto refers to a class other than the AbstractBaseUser.

2024-10-02 09:24 UTC, JelmenGuhlke commented
@cholakov11 so your suggestion is to use name the DTO `AbstractBaseUserDto` in this PR?

2024-10-07 12:02 UTC, cholakov11 commented
@JelmenGuhlke , yes. I have also implemented it this way.

2024-10-07 13:43 UTC, JelmenGuhlke requested changes
Changes LGTM -> please rebase the branch ontop of `main`

2024-10-07 13:43 UTC, JelmenGuhlke commented on MIGRATION.md
> +- `AppUserDto` classes in the subprojects `identity-model`, `sequence-model`, `uuid-model` have been renamed to
After a rebase on `main`, these changes are not required anymore, since the packages are deleted

2025-07-21 18:35 UTC, pwannenmacher commented on MIGRATION.md
> +- `AppUserDto` classes in the subprojects `identity-model`, `sequence-model`, `uuid-model` have been renamed to
I would suggest renaming it in a new PR. Since implementation, the underlying package structure has changed significantly, making a rebase nearly impossible.

2025-10-17 09:10 UTC, pwannenmacher commented
Solved in Version 3.1.0

2025-10-17 09:10 UTC, closed without merging